apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: thux
  labels:
    app: thux
    component: frontend
spec:
  type: NodePort
  ports:
  - port: 8000
  selector:
    app: thux
    component: frontend
