apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # namespace: thux
  name: hotlist-redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: thux
        component: hotlist-redis
        role: master
        # tier: backend
    spec:
      containers:
      - name: hotlist-redis
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
