apiVersion: v1
kind: Service
metadata:
  name: hotlist-redis
  namespace: thux
  labels:
    app: thux
    component: hotlist-redis
    # subcomponent: redis?
spec:
  ports:
  - port: 6379
  selector:
    app: thux
    component: hotlist-redis
