apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: inbox-redis
  namespace: thux
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: thux
        component: inbox-redis
    spec:
      containers:
      - name: thux-inbox-redis
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
