apiVersion: v1
kind: Service
metadata:
  name: inbox-redis
  namespace: thux
  labels:
    app: thux
    component: inbox-redis
spec:
  ports:
  - port: 6379
  selector:
    app: thux
    component: inbox-redis
