apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rebrow
  namespace: thux
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: thux
        component: rebrow
    spec:
      containers:
      - name: thux-rebrow
        image: marian/rebrow:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5001
