apiVersion: v1
kind: Service
metadata:
  name: rebrow
  labels:
    app: thux
    component: rebrow
spec:
  type: NodePort
  ports:
  - port: 5001
    nodePort: 30120
  selector:
    app: thux
    component: rebrow
