apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: resolver
  namespace: thux
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: thux
        component: resolver
      annotations:
        prometheus.io/scrape: 'true'
        # alpha/target.custom-metrics.podautoscaler.kubernetes.io: '{"items":[{"name":"qps", "value": "10"}]}'
        # metrics.alpha.kubernetes.io/custom-endpoints:
        #   # path: "/metrics",
        #   port: 9102
        #   names: ["myMetric"]
    spec:
      containers:
      - name: resolver
        image: giantswarm/thux-resolver
        # imagePullPolicy: Always
        volumeMounts:
          - name: metrics
            mountPath: /tmp
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
      - name: metrics
        image: dockermuenster/caddy:0.9
        command:
          - "caddy"
          - "-port=9102"
          - "-root=/var/www"
        ports:
          - containerPort: 9102
          # - hostPort: 9102
            #^ http://kubernetes.io/docs/user-guide/config-best-practices/
            # > Don’t use hostPort unless absolutely necessary, [..]
            # http://guoshimin.github.io/2016/06/03/custom-metrics.html
            # > [..], hence the need for hostPort.
        volumeMounts:
          - name: metrics
            mountPath: /var/www
      volumes:
        - name: metrics
          emptyDir:
            medium: Memory
