# apiVersion: v1
# kind: Service
# metadata:
#   name: resolver
#   labels:
#     app: thux
#     component: resolver
# spec:
#   type: NodePort
#   ports:
#   - port: 9102
#     nodePort: 30130
#   selector:
#     app: thux
#     component: resolver
