# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
#   #^ http://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/
#   # http://guoshimin.github.io/2016/06/03/custom-metrics.html
# metadata:
#   name: resolver-scaler
# spec:
#   scaleTargetRef:
#     kind: ReplicaSet
#     name: resolver
#   minReplicas: 3
#   maxReplicas: 10
#   targetCPUUtilizationPercentage: 50
