apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tracker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: thux
        component: tracker
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: tracker
        image: giantswarm/thux-tracker
        # imagePullPolicy: Always
        env:
        - name: TWITTER_TRACKING_QUERY
          value: http,https
        - name: TWITTER_CONSUMER_KEY
          valueFrom:
            secretKeyRef:
              name: twitter-api
              key: twitter-consumer-key
        - name: TWITTER_CONSUMER_SECRET
          valueFrom:
            secretKeyRef:
              name: twitter-api
              key: twitter-consumer-secret
        - name: TWITTER_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: twitter-api
              key: twitter-access-token
        - name: TWITTER_ACCESS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: twitter-api
              key: twitter-access-token-secret
        volumeMounts:
          - name: metrics
            mountPath: /tmp
      - name: metrics
        image: dockermuenster/caddy:0.9
        command:
          - "caddy"
          - "-port=9102"
          - "-root=/var/www"
        ports:
          - containerPort: 9102
        volumeMounts:
          - name: metrics
            mountPath: /var/www
      volumes:
        - name: metrics
          emptyDir:
            medium: Memory
