version: "2"
services:
  inbox-redis:
    image: redis:3.2-alpine

  tracker:
    build: tracker
    image: giantswarm/thux-tracker
    env_file: ../secrets/twitter-api-secret.env
      #^ provides secrets to access twitter api
    environment:
      TWITTER_TRACKING_QUERY: "http,https"

  resolver:
    build: resolver
    image: giantswarm/thux-resolver

  resolver-scaler:
    build: resolver-scaler
    image: giantswarm/thux-resolver-scaler

  hotlist-redis:
    image: redis:3.2-alpine

  cleaner:
    build: cleaner
    image: giantswarm/thux-cleaner

  rebrow:
    image: marian/rebrow:latest

  frontend:
    build: frontend
    image: giantswarm/thux-frontend
